### ISSUE TITLE
Not being able to save the game should log why

### ISSUE THREAD

**Issue by mafagafogigante** [mafagafogigante/dungeon#225]
The exception thrown should be logged.

**Comment by mafagafogigante** [comment]
Log snippet for the record

```
[2016-02-04 16:37:28] (INFO): Finished making the window. Took 345 ms.
[2016-02-04 16:37:29] (SEVERE): java.io.StreamCorruptedException: invalid stream header: 00012A6F
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at org.mafagafogigante.dungeon.io.Loader.loadFile(Loader.java:210)
	at org.mafagafogigante.dungeon.io.Loader.loadGame(Loader.java:121)
	at org.mafagafogigante.dungeon.game.Game.getInitialGameState(Game.java:87)
	at org.mafagafogigante.dungeon.game.Game.main(Game.java:59)

[2016-02-04 16:37:29] (INFO): Loaded 27 creature presets.
[2016-02-04 16:37:29] (INFO): Loaded 47 item presets.
[2016-02-04 16:37:29] (FINE): Added Potato to the inventory of Seth.
[2016-02-04 16:37:29] (INFO): Loaded 20 location presets.
[2016-02-04 16:37:29] (INFO): Set the GameState field in Game to a GameState.
[2016-02-04 16:37:29] (FINE): Added Dagger to the inventory of Merchant.
[2016-02-04 16:37:29] (INFO): Signaled the window to start accepting commands.
[2016-02-04 16:37:31] (FINE): "exit": started doInBackGround after 5 ms.
[2016-02-04 16:37:31] (FINE): "exit": started renderTurn after 12 ms.
[2016-02-04 16:37:31] (FINE): "exit": started processInput after 12 ms.
[2016-02-04 16:37:32] (INFO): Saved 68.2 kB in 119 ms.
[2016-02-04 16:37:32] (INFO): Closing instance. Ran for 4 seconds and 391 milliseconds. Parsed one command.
[2016-02-04 16:39:03] (INFO): Finished making the window. Took 394 ms.
[2016-02-04 16:39:05] (INFO): Loaded 27 creature presets.
[2016-02-04 16:39:05] (INFO): Loaded 47 item presets.
[2016-02-04 16:39:05] (FINE): Added Potato to the inventory of Seth.
[2016-02-04 16:39:05] (INFO): Loaded 20 location presets.
[2016-02-04 16:39:05] (INFO): Set the GameState field in Game to a GameState.
[2016-02-04 16:39:05] (INFO): Signaled the window to start accepting commands.
[2016-02-04 16:39:25] (FINE): "save": started doInBackGround after 5 ms.
[2016-02-04 16:39:25] (FINE): "save": started renderTurn after 13 ms.
[2016-02-04 16:39:25] (FINE): "save": started processInput after 14 ms.
[2016-02-04 16:39:25] (SEVERE): java.io.FileNotFoundException: saves/default.dungeon (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.mafagafogigante.dungeon.io.Loader.saveFile(Loader.java:237)
	at org.mafagafogigante.dungeon.io.Loader.saveGame(Loader.java:178)
	at org.mafagafogigante.dungeon.commands.CommandSets$20.execute(CommandSets.java:213)
	at org.mafagafogigante.dungeon.commands.PreparedIssuedCommand.execute(PreparedIssuedCommand.java:37)
	at org.mafagafogigante.dungeon.game.Game.processInput(Game.java:189)
	at org.mafagafogigante.dungeon.game.Game.renderTurn(Game.java:161)
	at org.mafagafogigante.dungeon.gui.GameWindow$4.doInBackground(GameWindow.java:238)
	at org.mafagafogigante.dungeon.gui.GameWindow$4.doInBackground(GameWindow.java:233)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
